# A "plugin" script to import RomM library items into ES-DE 🕹️
# GitHub: https://github.com/WirlyWirly/RomM-ES

# The placeholder files generated by GameImporter.py can later be used by GameStarter.py to fetch the actual rom files from RomM

__VERSION__ = 0.15

# ==================================== Package Imports ====================================

# Standard Library
import base64
import json
import logging as log
import re
import shutil
import sys
import time
import xml.etree.ElementTree as ET

from configparser import ConfigParser
from pathlib import Path

# Third-party
import requests 

# A basic logger
log.basicConfig(level=log.INFO, style='{', format='Line: {lineno} | level: {levelname} | Time: {asctime} | Info: {message}')


# ==================================== Functions ====================================

def createPlaceholderFile(placeholder_file, romm_id):
    # Check for and then create a placeholder file if no file exsists

    if placeholder_file.exists() == False:
        # No file exists where the placeholder should be, so create a placeholder

        placeholder_file.parents[0].mkdir(parents=True, exist_ok=True)
        with placeholder_file.open('w', encoding='UTF-8') as file:
            file.write(f"RomM-ES:{romm_id}")


def importPlatformGames(platform_id, platform_slug):
    # Get every game for the provided platform_id and add any missing games to ES-DE

    # ---------- Parse gamelist.xml ----------

    # The ES-DE gamelist.xml file can have illegal XML, so to avoid complicated work-arounds when using an XML parser, all parsing\modifications will be done with string formatting and regex
    gamelist_file = esde / f"gamelists/{mappings[platform_slug]['esde']}/gamelist.xml"

    log.debug(f'gamelist.xml: {gamelist_file}')

    # If the gamelist.xml does not exits, create it
    if gamelist_file.exists() == False:
        gamelist_file.parents[0].mkdir(parents=True, exist_ok=True)
        with gamelist_file.open('w', encoding='UTF-8') as file:
            file.write('<?xml version="1.0"?>\n<gameList>\n</gameList>')

    # Parse the existing gamelist.xml using bs4
    with gamelist_file.open('r', encoding='UTF-8') as xml:
        gamelist_xml = xml.read()

    # Get a list of existing <path> values, which will be used to prevent dupe entries in the <gameList> node
    existing_paths = re.findall(r'<path>(.*)</path>', gamelist_xml)

    # ---------- RomM Query ----------

    # Query RomM for all games for this platform
    response = requests.get(f'{romm_url}/api/roms?platform_ids={platform_id}&order_by=name&order_dir=asc&limit=10000', headers=romm_auth)
    platform_games = response.json()

    # Loop through every returned game and add it to ES-DE
    for game in platform_games['items']:

        # ---------- Placeholder File ----------

        # Create placeholder files in the ES-DE ROMs directories, which will later be used by 'GameStart.py' to fetch the rom files from RomM
        placeholder_file = roms_folder / f"{mappings[platform_slug]['esde']}/{game['fs_name']}"
        createPlaceholderFile(placeholder_file, game['id'])

        # ---------- Dupe Check ----------

        # Compare the RomM path to the existing paths in gamelist.xml path to check if the game is already listed
        gamefile_path = f"./{game['fs_name']}",
        gamefile_path = gamefile_path[0]

        if gamefile_path in existing_paths:
            # This rom path is already listed in the gamelist.xml, so continue to the next item to avoid a dupe
            log.debug(f'Dupe: {gamefile_path}')
            continue

        log.info(f"Importing: {game['name']}")
        # ---------- Game Metadata ----------

        # Milliseconds to seconds to date-string
        epoch_timestamp = game['metadatum']['first_release_date'] 

        if epoch_timestamp is None:
            release_date = None
        else:
            epoch_timestamp = epoch_timestamp / 1000
            release_date = time.strftime('%Y%m%dT000000', time.gmtime(epoch_timestamp))


        # Rating rounded to decimal
        rating = game['metadatum']['average_rating']

        if rating != None:
            rating = str(round(game['metadatum']['average_rating'] / 100, 1))


        # The game metadata that will be added to 'gamelist.xml'
        esde_metadata = {
            'name': game['name'],
            'releasedate': release_date,
            'path': gamefile_path,
            'rating': rating,
            'publisher': game['ss_metadata']['companies'][0] if len(game['ss_metadata']['companies']) > 0 else None, 
            'developer': game['ss_metadata']['companies'][1] if len(game['ss_metadata']['companies']) > 1 else None,
            'players': game['metadatum']['player_count'],
            'genre': game['metadatum']['genres'][0] if len(game['metadatum']['genres'][0]) > 0 else None,
            'favorite': 'false',
            'desc': game['summary'],
        }

        # ---------- Create <game> Entry ----------

        # Create the new <game> element and append it to the <gameList> node

        new_element = '	<game>'
        for key, value in esde_metadata.items():
            if value is None:
                # No metadata value, so don't create a element
                continue

            new_element = new_element + f'\n		<{key}>{value}</{key}>'

        new_element = new_element + '\n	</game>'

        # Append the new <game> elements just above the </gameList> element
        gamelist_xml = re.sub('</gameList>', new_element + '\n</gameList>', gamelist_xml)

        # ---------- Download Media ----------

        # Download the game artwork from RomM and place it in the appropriate ES-DE directories

        media_urls = {
            '3dboxes': game['ss_metadata']['box3d_path'] if config['MediaTypes']['3dboxes'] == 'true' else None,
            'backcovers': game['ss_metadata']['box2d_back_path'] if config['MediaTypes']['backcovers'] == 'true' else None,
            'covers': game['path_cover_large'] if config['MediaTypes']['covers'] == 'true' else None,
            'fanart': game['ss_metadata']['fanart_path'] if config['MediaTypes']['fanart'] == 'true' else None,
            'manuals': game['path_manual'] if config['MediaTypes']['manuals'] == 'true' else None,
            'marquees': game['ss_metadata']['logo_path'] if config['MediaTypes']['marquees'] == 'true' else None,
            'miximages': game['ss_metadata']['miximage_path'] if config['MediaTypes']['miximages'] == 'true' else None,
            'physicalmedia': game['ss_metadata']['physical_path'] if config['MediaTypes']['physicalmedia'] == 'true' else None,
            'screenshots': ( game['merged_screenshots'][0] if len(game['merged_screenshots']) > 0 else None ) if config['MediaTypes']['screenshots'] == 'true' else None,
            'titlescreens': game['ss_metadata']['title_screen_path'] if config['MediaTypes']['titlescreens'] == 'true' else None,
            'videos': game['path_video'] if config['MediaTypes']['videos'] == 'true' else None
        }

        for key, value in media_urls.items():
            # Prepare, parse, and then download each item in media_urls

            if (value is None) or (value == ''):
                # RomM has no media for this artwork type, so do nothing
                continue

            media_url = value
            if re.match(r'^/assets/', media_url) is None:
                # The media URL needs to be prepended with /assets/
                media_url = f'/assets/romm/resources/{value}'

            # Complete the url with the RomM domain
            media_url = f'{romm_url}{media_url}'
            log.debug(f'mediaURL: {media_url}')

            # The extension to use when saving the media
            extension = re.search(r'\.(png|webp|jpg|gif|jxl|mp4)', media_url)[1]

            # The path for where the media file will be saved
            media_file = downloaded_media / f"{mappings[platform_slug]['esde']}/{key}/{game['fs_name_no_ext']}.{extension}"
            media_file.parents[0].mkdir(parents=True, exist_ok=True)

            # GET and then save the media_url as media_file
            response = requests.get(media_url, headers=romm_auth)
            with media_file.open('wb') as file:
                file.write(response.content)


    # Update gamelist.xml with the new <game> elements
    with gamelist_file.open('w', encoding='UTF-8') as file:
        file.write(gamelist_xml)


# ==================================== Main ====================================

# The absolute path to the RomM-ES directory
romm_es = Path(sys.argv[0]).resolve().parents[0]

log.debug(f'RomM-ES Path: {romm_es}')

# ---------- Load Settings ----------

# Load the options in the 'settings.ini' file
config_file = romm_es / 'settings.ini'
if config_file.exists() == False:
    # The 'settings.ini' file does not exists, so create it and then exit

    settings_template = '''[Required]
# The RomM URL and ApiToken
romm_url = http://localhost:8080
romm_apitoken = abc123

# The absolute path to the ES-DE ROMs folder
esde_roms_folder = C:/path/to/ROMs/


[General]
# The absolute path to the ES-DE data folder, if the RomM-ES folder is not already inside it
esde_data_folder = C:/path/to/ES-DE/

# Setting this to 'true' will supersede individual platform settings below and import games from all supported platforms
import_all_platforms = true

# The absolute path to 7zip, if it is not already in the RomM-ES folder
7zip = C:/path/to/7z.exe


[MediaTypes]
# The types of media\\artwork that will be downloaded from RomM during import
3dboxes = true
backcovers = true
covers = true
fanart = true
manuals = true
marquees = true
miximages = true
physicalmedia = true
screenshots = true
titlescreens = true
videos = true


[ImportPlatforms]
# The RomM platforms whose games will be imported into ES-DE
gba = false
n64 = false 
nds = false 
ngc = false
ps2 = false
psp = false
xbox = false
'''
    with config_file.open('w', encoding='UTF-8') as file:
        file.write(settings_template)
    input("\nThe 'settings.ini' file has been created in the RomM-ES directory.\n\nUpdate the defaults in the [Required] section and any other optional settings")
    sys.exit()

config = ConfigParser()
config.read(config_file)

# The ES-DE directory and relevant child directories
esde = Path(sys.argv[0]).resolve().parents[1]

if esde.name != 'ES-DE':
    esde = Path(config['General']['esde_data_folder']).resolve()

roms_folder = Path(config['Required']['esde_roms_folder'])
gamelists = esde / 'gamelists'
downloaded_media = esde / 'downloaded_media'

# Read the mapped RomM to ES-DE platform slugs
platform_maps = romm_es / 'platformMaps.json'
with platform_maps.open('r', encoding='utf-8') as file:
    mappings = json.load(file)

# ---------- RomM Importing ----------

romm_url = config['Required']['romm_url']
romm_api = config['Required']['romm_apitoken']

romm_auth = { 'Authorization': f'Bearer {romm_api}' }

# Get all RomM platforms
response = requests.get(f'{romm_url}/api/platforms', headers=romm_auth)
platforms = response.json()

# Import games for each enabled platform
import_all_platforms = True if config['General']['import_all_platforms'] == 'true' else False
for platform in platforms:

    # The RomM platform slug 
    platform_slug = platform['fs_slug']

    if platform_slug not in config['ImportPlatforms']:
        # This platform is not supported for import by RomM-ES
        log.info(f'Unsupported Import Platform: {platform_slug}')
        continue

    elif (import_all_platforms == False) and (config['ImportPlatforms'][platform_slug] != 'true'):
        # No, the games in this platform should not be imported
        log.info(f'Skipping Import Platform: {platform_slug}')
        continue

    elif (import_all_platforms == True) or config['ImportPlatforms'][platform_slug] == 'true':
        # Yes, the games in this platform should be imported into ES-DE
        log.info(f'==================== {platform_slug} ====================')

        importPlatformGames(platform['id'], platform_slug)
