# A "plugin" script to import RomM library games into ES-DE 🕹️
# GitHub: https://github.com/WirlyWirly/RomM-ES

# The byte-sized placeholder files generated by GameImporter.py can later be used by 'GameStarter.py' to download the actual rom files from RomM

__VERSION__ = 0.2

# ==================================== Package Imports ====================================

# Standard Library
import json
import logging as log
import os
import re
import sys
import time

from configparser import ConfigParser
from pathlib import Path

# Third-party
import requests 

# A basic logger
log.basicConfig(level=log.INFO, style='{', format='Line: {lineno} | level: {levelname} | Time: {asctime} | Info: {message}')


# ==================================== Functions ====================================

def createPlaceholderFile(placeholder_file, romm_id, romm_extension=None):
    # Create or update a RomM placeholder file

    if placeholder_file.exists() == False:
        # No file exists where the placeholder should be, so create a placeholder

        placeholder_file.parent.mkdir(parents=True, exist_ok=True)
        with placeholder_file.open('w', encoding='UTF-8') as file:

            if extract_file == False:
                file.write(f'RomM-ES:{romm_id}')
            else:
                file.write(f'RomM-ES:{romm_id}:{romm_extension}')

            log.debug(f'Placeholder: "{placeholder_file}"')

    elif os.path.getsize(placeholder_file) > 20:
        # This file is too large to be a placeholder file, so do nothing
        return

    else:

        # This game file is small enough to be a placeholder file, so parse it for verification
        placeholder_id = None
        with placeholder_file.open('r', encoding='UTF-8') as file:

            # Search the contents of the file for a RomM id number
            placeholder_id = re.search('^RomM-ES:(\d+)$', file.read())

        if placeholder_id is None:
            # This file does not contain a RomM id, so do nothing
            return

        else:
            # Yes, this is a RomM placeholder file, so update the RomM id
            placeholder_id = int(placeholder_id[1])

            with placeholder_file.open('w', encoding='UTF-8') as file:

                if extract_file == False:
                    file.write(f'RomM-ES:{romm_id}')
                else:
                    # Save the RomM file extension along with the RomM id
                    file.write(f'RomM-ES:{romm_id}:{romm_extension}')


def importGame(game, existing_paths):
    # Add the provided RomM game json to the gamelist.xml string

    # ---------- Placeholder File ----------

    # Create placeholder files in the ES-DE ROMs directories, which will later be used by 'GameStart.py' to fetch the rom files from RomM
    placeholder_file = roms_folder / f"{mappings[platform_slug]['esde']}/{game['fs_name']}"

    # Change the extension of the placeholder file to match what will be extracted
    if extract_file == False:
        createPlaceholderFile(placeholder_file, game['id'])
    else:
        placeholder_file = placeholder_file.parent / f"{placeholder_file.stem}.{config['ExtractedExtension'][platform_slug]}"
        romm_extension = re.search(r'\.\w+?$', game['fs_name'])
        createPlaceholderFile(placeholder_file, game['id'], romm_extension)

    # ---------- Dupe Check ----------

    # Compare the RomM path to the existing paths in gamelist.xml path to check if the game is already listed
    gamefile_path = f"./{game['fs_name']}",
    gamefile_path = gamefile_path[0]

    # Check if this platform has a specified extension indicating extraction
    if extract_file == True:
        gamefile_path = re.sub(r'\.\w+?$', f".{config['ExtractedExtension'][platform_slug]}", gamefile_path)

    if gamefile_path in existing_paths:
        # This rom path is already listed in the gamelist.xml, so continue to the next item to avoid a dupe
        log.debug(f'Duplicate: {gamefile_path}')
        return 'duplicate'

    if extract_file == False:
        print(f"+ {game['fs_name']}")
    else:
        print(f"+ [{config['ExtractedExtension'][platform_slug]}] {game['fs_name']}")

    log.debug(f"Importing: {game['fs_name']}")

    # ---------- Game Metadata ----------

    # Milliseconds to seconds to date-string
    epoch_timestamp = game['metadatum']['first_release_date'] 

    if epoch_timestamp is None:
        release_date = None
    else:
        epoch_timestamp = epoch_timestamp / 1000
        release_date = time.strftime('%Y%m%dT000000', time.gmtime(epoch_timestamp))


    # Rating rounded to decimal
    rating = game['metadatum']['average_rating']

    if rating != None:
        rating = str(round(game['metadatum']['average_rating'] / 100, 1))


    # The game metadata that will be added to 'gamelist.xml'
    esde_metadata = {
        'name': game['name'],
        'releasedate': release_date,
        'path': gamefile_path,
        'rating': rating,
        'publisher': game['ss_metadata']['companies'][0] if len(game['ss_metadata']['companies']) > 0 else None, 
        'developer': game['ss_metadata']['companies'][1] if len(game['ss_metadata']['companies']) > 1 else None,
        'players': game['metadatum']['player_count'],
        'genre': game['metadatum']['genres'][0] if len(game['metadatum']['genres'][0]) > 0 else None,
        'favorite': 'false',
        'desc': re.sub(r'\r', '', game['summary']), # Remove the trailing '^M' newline characters
    }

    # ---------- Download Media ----------

    # Download the game artwork from RomM and place it in the appropriate ES-DE directories

    media_urls = {
        '3dboxes': game['ss_metadata']['box3d_path'] if config['MediaTypes']['3dboxes'] == 'true' else None,
        'backcovers': game['ss_metadata']['box2d_back_path'] if config['MediaTypes']['backcovers'] == 'true' else None,
        'covers': game['path_cover_large'] if config['MediaTypes']['covers'] == 'true' else None,
        'fanart': game['ss_metadata']['fanart_path'] if config['MediaTypes']['fanart'] == 'true' else None,
        'manuals': game['path_manual'] if config['MediaTypes']['manuals'] == 'true' else None,
        'marquees': game['ss_metadata']['logo_path'] if config['MediaTypes']['marquees'] == 'true' else None,
        'miximages': game['ss_metadata']['miximage_path'] if config['MediaTypes']['miximages'] == 'true' else None,
        'physicalmedia': game['ss_metadata']['physical_path'] if config['MediaTypes']['physicalmedia'] == 'true' else None,
        'screenshots': ( game['merged_screenshots'][0] if len(game['merged_screenshots']) > 0 else None ) if config['MediaTypes']['screenshots'] == 'true' else None,
        'titlescreens': game['ss_metadata']['title_screen_path'] if config['MediaTypes']['titlescreens'] == 'true' else None,
        'videos': game['path_video'] if config['MediaTypes']['videos'] == 'true' else None
    }

    for key, value in media_urls.items():
        # Prepare, parse, and then download each item in media_urls

        if (value is None) or (value == ''):
            # RomM has no media for this artwork type, so do nothing
            continue

        media_url = value
        if re.match(r'^/assets/', media_url) is None:
            # The media URL needs to be prepended with /assets/
            media_url = f'/assets/romm/resources/{value}'

        # Complete the url with the RomM domain
        media_url = f'{romm_url}{media_url}'
        log.debug(f'mediaURL: {media_url}')

        # The extension to use when saving the media
        extension = re.search(r'\.(png|webp|jpg|gif|jxl|mp4)', media_url)[1]

        # The path for where the media file will be saved
        media_file = downloaded_media / f"{mappings[platform_slug]['esde']}/{key}/{game['fs_name_no_ext']}.{extension}"
        media_file.parents[0].mkdir(parents=True, exist_ok=True)

        # GET and then save the media_url as media_file
        response = requests.get(media_url, headers=romm_auth)
        with media_file.open('wb') as file:
            file.write(response.content)

    # ---------- Create <game> Entry ----------

    # Create the new <game> element that will be appended to the <gameList> node
    new_game_xml = '	<game>'
    for key, value in esde_metadata.items():
        if value is None:
            # No metadata value, so don't create a element
            continue

        new_game_xml = new_game_xml + f'\n		<{key}>{value}</{key}>'

    new_game_xml = new_game_xml + '\n	</game>'

    # Replace '&' with the XML safe '&amp;'
    new_game_xml = re.sub(r"&", '&amp;', new_game_xml)

    log.debug(new_game_xml)

    return new_game_xml


def importPlatformGames(platform_id, platform_slug):
    # Get every game for the provided platform_id and add any missing games to ES-DE

    # ---------- Parse gamelist.xml ----------

    # The ES-DE gamelist.xml file can have illegal XML, so to avoid complicated work-arounds when using an XML parser, all parsing\modifications will be done with string formatting and regex
    gamelist_file = esde / f"gamelists/{mappings[platform_slug]['esde']}/gamelist.xml"

    log.debug(f'gamelist.xml: {gamelist_file}')

    # If the gamelist.xml does not exits, create it
    if gamelist_file.exists() == False:
        gamelist_file.parents[0].mkdir(parents=True, exist_ok=True)
        with gamelist_file.open('w', encoding='UTF-8') as file:
            file.write('<?xml version="1.0"?>\n<gameList>\n</gameList>')

    # Parse the existing gamelist.xml using bs4
    with gamelist_file.open('r', encoding='UTF-8') as xml:
        gamelist_xml = xml.read()

    # Get a list of existing <path> values, which will be used to prevent dupe entries in the <gameList> node
    existing_paths = re.findall(r'<path>(.*)</path>', re.sub(r'&amp;', '&', gamelist_xml)) # Replace the '&amp;' in the parsed paths with actual '&'

    # ---------- RomM Query ----------

    # Query RomM for all games for this platform
    response = requests.get(f'{romm_url}/api/roms?platform_ids={platform_id}&order_by=name&order_dir=asc&limit=10000', headers=romm_auth)
    platform_games = response.json()

    if extract_file == True:
        print(f"\nRomM Game Count: {len(platform_games['items'])}")
        print(f"Extracted Extension: {config['ExtractedExtension'][platform_slug]}\n")
    else: 
        print(f"\nRomM Game Count: {len(platform_games['items'])}\n")

    # Import Stat Tracker
    new_game_count = 0
    duplicate_count = 0

    # Loop through every returned game and parse the metadata to add it to ES-DE
    for game in platform_games['items']:

        # Generate the <game> xml block, media, and placeholder files
        new_game_xml = importGame(game, existing_paths)

        if new_game_xml == "duplicate":
            # This game is a duplicate of an already existing gamelist.xml entry
            duplicate_count += 1
            continue

        else:
            # Append the new <game> xml block just above the </gameList> element
            new_game_count += 1
            gamelist_xml = re.sub('</gameList>', new_game_xml + '\n</gameList>', gamelist_xml)

    # Update the contents of gamelist.xml to include all the new <game> blocks
    with gamelist_file.open('w', encoding='UTF-8') as file:
        file.write(gamelist_xml)

    print(f"""\n----- DONE -----
Imported Games: {new_game_count}
Duplicate Games: {duplicate_count}\n\n""")



# ==================================== Main ====================================

print(f"""
--------------------------------------------------------------
      _____                 __  __        ______  _____ 
     |  __ \               |  \/  |      |  ____|/ ____|
     | |__) |___  _ __ ___ | \  / |______| |__  | (___  
     |  _  // _ \| '_ ` _ \| |\/| |______|  __|  \___ \ 
     | | \ \ (_) | | | | | | |  | |      | |____ ____) |
     |_|  \_\___/|_| |_| |_|_|  |_|      |______|_____/ 
                                                    
                        version {__VERSION__}
-------------------------------------------------------------- """)

# The absolute path to the RomM-ES directory
romm_es = Path(sys.argv[0]).resolve().parents[0]

log.debug(f'RomM-ES Path: {romm_es}')

# ---------- Load Settings ----------

# Load the options in the 'settings.ini' file
config_file = romm_es / 'settings.ini'
if config_file.exists() == False:
    # The 'settings.ini' file does not exists, so create it and then exit

    settings_template = '''[Required]
# The RomM URL and ApiToken
romm_url = http://localhost:8080
romm_apitoken = abc123

# The absolute path to the ES-DE ROMs folder
esde_roms_folder = C:/path/to/ROMs/


[General]
# The absolute path to the ES-DE data folder, if the RomM-ES folder is not already inside it
esde_data_folder = C:/path/to/ES-DE/

# Setting this to 'true' will supersede individual platform settings below and import games from all supported platforms
import_all_platforms = true

# The absolute path to 7zip, if it is not already in the RomM-ES folder
7zip = C:/path/to/7z.exe


[MediaTypes]
# The types of media\\artwork that will be downloaded from RomM during import
3dboxes = true
backcovers = true
covers = true
fanart = true
manuals = true
marquees = true
miximages = true
physicalmedia = true
screenshots = true
titlescreens = true
videos = true


[ImportPlatforms]
# The RomM platforms whose games will be imported into ES-DE
3ds = false
c64 = false
dc = false
gb = false
gba = false
gbc = false
n64 = false
nds = false
nes = false
ngc = false
ps2 = false
ps3 = false
ps4 = false
psp = false
psvita = false
psx = false
saturn = false
snes = false
switch = false
wii = false
wiiu = false
xbox = false
xbox360 = false
xboxone = false
'''
    with config_file.open('w', encoding='UTF-8') as file:
        file.write(settings_template)
    input("\nThe 'settings.ini' file has been created in the RomM-ES directory.\n\nUpdate the defaults in the [Required] section and any other optional settings")
    sys.exit()

config = ConfigParser()
config.read(config_file)

# The ES-DE directory and relevant child directories
esde = Path(sys.argv[0]).resolve().parents[1]

if esde.name != 'ES-DE':
    esde = Path(config['General']['esde_data_folder']).resolve()

roms_folder = Path(config['Required']['esde_roms_folder'])
gamelists = esde / 'gamelists'
downloaded_media = esde / 'downloaded_media'

# Read the mapped RomM to ES-DE platform slugs
platform_maps = romm_es / 'platformMaps.json'
with platform_maps.open('r', encoding='utf-8') as file:
    mappings = json.load(file)

# ---------- RomM Importing ----------

romm_url = config['Required']['romm_url']
romm_api = config['Required']['romm_apitoken']

romm_auth = { 'Authorization': f'Bearer {romm_api}' }

# Get all RomM platforms
response = requests.get(f'{romm_url}/api/platforms', headers=romm_auth)
platforms = response.json()

# Import games for each enabled platform
import_all_platforms = True if config['General']['import_all_platforms'] == 'true' else False

print(f"""
RomM Platforms: {len(platforms)}
""")

log.debug(f'RomM Platforms: {len(platforms)} {platforms}')
for platform in platforms:

    # The RomM platform slug 
    platform_slug = platform['fs_slug']

    if platform_slug not in config['ImportPlatforms']:
        # This platform is not supported for import by RomM-ES
        print(f'?????????? Unsupported: {platform_slug} ??????????\n\n')
        log.debug(f'?????????? Unsupported: {platform_slug} ??????????')
        continue

    elif (import_all_platforms == False) and (config['ImportPlatforms'][platform_slug] != 'true'):
        # No, the games in this platform should not be imported
        print(f'.......... Disabled: {platform_slug} ..........\n\n')
        log.debug(f'.......... Disabled: {platform_slug} ..........')
        continue

    elif (import_all_platforms == True) or config['ImportPlatforms'][platform_slug] == 'true':
        # Yes, the games in this platform should be imported into ES-DE
        print(f"========== {platform['name']} [{platform_slug}] ==========")
        log.debug(f"========== {platform['name']} [{platform_slug}] ==========")

        # Check if this platform has a specified extension indicating extraction
        extract_file = False
        if config['ExtractedExtension'][platform_slug] != '':
            extract_file = True

        importPlatformGames(platform['id'], platform_slug)
